all:
	gcc -o modulonet_run main.c modulonet.c layer_ops.c utils.c matmul.c ../includes/modulonet.h ../includes/layer_ops.h ../includes/globals.h ../includes/utils.h ../includes/matmul.h

clean:
	rm modulonet_run
